### PR TITLE
Prepare a new release 2.8

### PR DESCRIPTION
**Pull request by northwestwitch**
### Added
- .cff citation file and doi badge on readme page
- GitHub action to publish repo to PyPI when a new release is created
### Fixed
- Fixed in README file the server port used by the web server container launched from docker-compose
- Provide a content type description for long_description in setup file

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by northwestwitch** [comment]
Looks like the PyPI action has worked, finally: 
image

This was painful! :)

**Comment by henrikstranneheim** [comment]
I added a setting that the github branch is deleted on merge. Revert it if you want

**Comment by northwestwitch** [comment]
I'd like to keep the branches that were used as release targets. The others can be removed. How do we change it back?

**Comment by henrikstranneheim** [comment]
You can always restore them anyway. I have changed it back now - it is as before

**Pull request merged**
