### PR TITLE
Docker updates

### PR DESCRIPTION
**Pull request by tsnowlan**
Dockerfile got a little broken, so decided to clean things up while I was at it. Using conda environment file to manage everything, which can be regenerated from the requirements files by `docker/update_env.sh`.

As I was testing, I found that pytest-cov 2.6.0 broke on some deprecated functions that finally got removed from pytest. Upgrading to 2.6.1 fixes that, so updated the requirements-dev.txt with that as well.

### CODE REVIEW

**Comment by tsnowlan** [comment]
Ah, looks like pytest 4 is not being installed by the CI, though it was on the docker image. What version do you have running in production? We can pin to that and see what version of pytest-cov it needs.

**Comment by northwestwitch** [comment]
I'll check. I'm afraid we have a quite old version in stage/production. I'll let you know!

**Comment by northwestwitch** [comment]
Looks like we have pytest==4.4.1 on the stage environment where the software should run

**Comment by northwestwitch** [comment]
I think it's fine to merge if it's working!

**Comment by tsnowlan** [comment]
Good, that cleared it up. Yeah, sounds good to me.

**Pull request merged**
